### ISSUE TITLE
Load svg data

### ISSUE THREAD

**Issue by SyZn** [mozman/svgwrite#13]
It would be a nice option to import/load an SVG file (if you want to modify an existing file).

**Comment by mozman** [comment]
I purposely chose the name _svgwrite_ because reading/importing SVG data was never planned.

**Comment by mkv123** [comment]
FYI:

I needed to inject fragments of existing svg data into my "main" svg which is generated using svgwrite. Basically, I had a bunch of symbols in separate svg files that I wanted to add to the defs section in order to <use> them later.

I did it by by creating an element called External, which takes an ElementTree Element in the constructor.
 
```
class External(svgwrite.container.Group):
    def __init__(self, xml, **extra):
        self.xml = xml

        # Remove namespace
        ns = u'{http://www.w3.org/2000/svg}'
        nsl = len(ns)
        for elem in self.xml.getiterator():
            if elem.tag.startswith(ns):
                elem.tag = elem.tag[nsl:]

        super(External, self).__init__(**extra)

    def get_xml(self):
        return self.xml
```
