### ISSUE TITLE
save() is very slow

### ISSUE THREAD

**Issue by mheden** [mozman/svgwrite#25]
It feels like the `save()` function is a magnitude too slow:

```py
import svgwrite
import time

size = 100
d = svgwrite.Drawing('example.svg', (size, size))

t1 = time.time()
for y in range(size):
    for x in range(size):
        d.add(d.path(d="M %d %d L %d %d" % (x, y, y, x),  stroke='#888'))
t2 = time.time()
d.save()
t3 = time.time()

print("create:", t2-t1)
print("save:", t3-t2)
```` 

The above example gives the following output (together with a ~400kB SVG file):
```
create: 0.5911922454833984
save: 22.79025411605835
```
When doing a profile of the code it seems the problem is `etree.tostring()` so I guess the issue should go there instead, but is it possible to do improve something about this in the `svgwrite` as well?

**Comment by j2kun** [comment]
This is caused by a bad dependency on pyparsing. The code used to parse that the path data is valid calls pyparsing, which is a notoriously slow library.

I have a [patched fork](https://github.com/j2kun/svgwrite/) that removes the dependency, but I am not going to guarantee its maintenance over time.

**Comment by mozman** [comment]
The same is accomplished by setting debug=False in svgwrite.Drawing() without removing the whole validator.

**Comment by j2kun** [comment]
Well that is much easier. @mozman this is such an egregious difference in runtime and well hidden in your code that you should really consider documenting it explicitly or changing the default, because debug mode is on by _default_.

**Comment by mozman** [comment]
Help on documentation is also appreciated ;).

**Comment by j2kun** [comment]
Wouldn't you rather turn off debug mode by default? I tried changing debug=False in params.py, and it worked, but too many tests started failing and it was unclear where to insert "debug=True" to get them to pass again. I suppose I could also turn it off by default just in the Drawing class init...

**Comment by mozman** [comment]
No, this is the default behavior since 2010.

Btw svgwrite without validation is just an ElementTree() wrapper, which is really pointless. If you don't need validation, I would suggest to create your  SVG by ElementTree() without an additional dependency, and as bonus you could use the lxml package which is really fast.

**Comment by j2kun** [comment]
I only use this library for the helpers to make creating svgs more readable, e.g., push_arc and friends, which AFAICT are syntactically valid by construction. I'm quite happy with [the results](https://github.com/j2kun/hyperbolic-experiments/blob/master/tessellation.py#L144-L200). Using etree defeats readability.

I can live with setting debug=False.

**Comment by shrx** [comment]
Setting `debug=False` reduced the saving time from 40 to 0.3 seconds in my case!
