### ISSUE TITLE
No visible text in svgwrite.Drawing().textArea()

### ISSUE THREAD

**Issue by cclauss** [mozman/svgwrite#30]
The code below writes out a file named __no_textArea.svg__ which when rendered displays the __text__ string but the __textArea__ string is not displayed.  What am I doing wrong?
```python
import svgwrite  # pip install svgwrite

MAX_PIXELS = 1000

def make_drawing(filename="no_textArea.svg"):
    dwg = svgwrite.Drawing(filename, size=(MAX_PIXELS, MAX_PIXELS), profile="tiny")
    dwg.viewbox(0, 0, MAX_PIXELS, MAX_PIXELS)
    dwg.add(dwg.rect(size=('100%', '100%'), fill="lightgrey", class_='background'))

    dwg.add(dwg.text(text="Here is text", fill="darkblue", insert=("2%", "2%")))
    dwg.add(dwg.textArea(text="But no textArea\nDown below!", fill="darkblue",
                         insert=("2%", "20%"), size=("80%", "80%"), profile="tiny"))
    return dwg

make_drawing().save()
```
https://stackoverflow.com/questions/49449460/how-to-implement-svgwrite-textarea-in-python was the closest question that I could find on Stack Overflow but that did not get answered.

**Comment by rawlins** [comment]
I'm new to `svgwrite` but I've also been doing some text rendering things with it. I suspect this problem is not really about svgwrite, but about whatever you are using to view the svg itself. For example, `textArea` systematically doesn't work for me on firefox, and I can't even get the [w3 doc example](https://www.w3.org/TR/SVGMobile12/text.html#TextAreaElement) for `textArea` to render. It also looks to me like your code generates perfectly reasonable svg, it's just not a well-supported svg feature (it doesn't render for me in firefox either; haven't checked other browsers). Maybe try an authoring tool like inkscape if you haven't?

Also, this element seems to be [going away](https://www.w3.org/Graphics/SVG/WG/wiki/SVG2_Requirements_Input#the_textArea_element) entirely in SVG 2, so I bet most browsers won't be in a hurry to implement it if they haven't already.

**Comment by cclauss** [comment]
I did try Mac Firefox, Safari, and Chrome without success.  I will post an example that implements a workaround.
