### ISSUE TITLE
Expose ElementTrees xml_declaration option

### ISSUE THREAD

**Issue by tdapper** [mozman/svgwrite#33]
We are having a few problems because of SVG files not having a proper xml document header similar to this:
`<?xml version="1.0" encoding="UTF-8" ?>`

ElementTree (which I believe is what svgwrite is based on) apparently skips that if the encoding is UTF-8. There is a flag, though, that let's you force ElementTree.write() to always include it. It would be cool, if that flag were exposed by `Drawing::save()` and `Drawing::saveAs()`. That might also be a better way of manually adding the encoding in `Drawing::write()`.

**Comment by mozman** [comment]
svgwrite writes the xml header

**Comment by tdapper** [comment]
OK, just to elaborate:

Part of this was indeed our mistake of using `Drawing::tostring()`, which I guess is supposed to produce something that can be inlined into another XML which in turn requires it to *not* to have the header. We did this because we needed the file in a memory buffer. We now moved that to using `Drawing::write()` and piping it into a string via `StringIO` and that works as expected.

However, you are manually adding the xml header to the file when it gets written in `drawing.py` l. 98. I think the more robust way of doing it would be to use the `xml_declaration=True` argument to `ElementTree::write()`.

After I wrote the last paragraph, I see that is not possible because you get a string and use that to pretty-print it (which is apparently not an option of `ElementTree`).

So yes, the way you did it is probably the only way. Only suggestion that remains would be to perhaps supply encoding in your call to `self.tostring()` in l. 109. From the Python documentation it appears the encoding of that function defaults to US-ASCII instead of UTF-8.

See:
https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write

P.S.: Great work with svgwrite!

**Comment by mozman** [comment]
Hi!

svgwrite do not use ElementTree.write(), because I don't know how to add style sheet declarations

> \<?xml-stylesheet href=... ?\>

But even if there is a solution for style sheet declarations, the work flow would be:

- create xml tree with all required components
- ElementTree.write() into a string
- pretty format xml
- write to file

not really better, just another way

BaseElement.tostring() returns an unicode string in a very inefficient way, but that is the price for Python 2 and Python 3 compatibility.

STOP USING PYTHON 2 - especially for handling strings

I will remove Python 2 support in svgwrite with the next bigger feature update, maybe SVG2 support, but not in the near future.
