### ISSUE TITLE
Entities in Drawing.text are escaped and thus unuseable

### ISSUE THREAD

**Issue by Sojourneer** [mozman/svgwrite#71]
I'm trying to include HTML entities, e.g. **&amp;#176;** in the text of a text node created by Drawing.text(mytext).  The saved svg file has **&amp;amp;#176;**

It is possible to get the entities to go through unaltered?

**Comment by jotaf98** [comment]
Hi, I guess you could take part of the hack proposed in #70 to achieve this. In that case, the XML writing method is overriden to insert a full XML sub-tree instead of a simple (escaped) text. The XML sub-tree is obtained by parsing a string. So basically you create a class to replace Text that has the behavior you want.
